# Generated by Django 2.1.7 on 2019-04-02 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('cost', models.TextField()),
                ('os', models.TextField()),
                ('screen_res', models.TextField()),
                ('camera_res', models.TextField()),
                ('mem', models.TextField()),
                ('processor', models.TextField()),
                ('glonas', models.TextField()),
                ('beidou', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Alcatel',
            fields=[
                ('phone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phones.Phone')),
                ('fm_radio', models.TextField()),
                ('flashlight', models.TextField()),
            ],
            bases=('phones.phone',),
        ),
        migrations.CreateModel(
            name='Motorola',
            fields=[
                ('phone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phones.Phone')),
                ('fm_radio', models.TextField()),
                ('gyro', models.TextField()),
            ],
            bases=('phones.phone',),
        ),
        migrations.CreateModel(
            name='Xiaomi',
            fields=[
                ('phone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phones.Phone')),
                ('a2dp', models.TextField()),
                ('irda', models.TextField()),
            ],
            bases=('phones.phone',),
        ),
    ]
