# Generated by Django 2.2 on 2019-04-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190407_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
        migrations.AddField(
            model_name='scope',
            name='chief',
            field=models.BooleanField(default=0, verbose_name='Основной'),
            preserve_default=False,
        ),
    ]
