# Generated by Django 2.2 on 2019-04-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20190407_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='chief',
            field=models.BooleanField(default=0, verbose_name='Основной'),
            preserve_default=False,
        ),
    ]
