# Generated by Django 2.2 on 2019-04-07 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_remove_scope_chief'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='chief',
            new_name='main',
        ),
    ]
