# Generated by Django 2.2 on 2019-04-07 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20190407_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='name',
            new_name='topic',
        ),
    ]
