# Generated by Django 2.2 on 2019-05-29 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csvpath',
            options={'verbose_name': 'Путь', 'verbose_name_plural': 'Путь'},
        ),
    ]
