# Generated by Django 2.2 on 2019-04-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=96, verbose_name='Заголовок статьи')),
                ('img', models.FileField(upload_to='docs/article/img/%Y/%m/%d/', verbose_name='URL изображения')),
                ('text', models.TextField(verbose_name='Текст статьи')),
                ('paid', models.BooleanField(default=False, verbose_name='Платный ресурс')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session', models.CharField(max_length=96, verbose_name='Идентификатор сессии')),
                ('signed', models.BooleanField(default=False, verbose_name='Подписан')),
            ],
        ),
    ]
