# Generated by Django 2.2 on 2019-05-17 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20190517_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='registered_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='signed',
            field=models.BooleanField(default=False, verbose_name='Подписка'),
        ),
    ]
