# Generated by Django 2.2 on 2019-04-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Число')),
                ('state', models.IntegerField(default=0, verbose_name='Код состояния')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session', models.CharField(max_length=96, verbose_name='Идентификатор сессии')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
            },
        ),
        migrations.CreateModel(
            name='PlayerGameInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.IntegerField(verbose_name='Число попыток')),
                ('creator', models.ManyToManyField(related_name='creators', to='game.Player')),
                ('opponent', models.ManyToManyField(related_name='opponents', to='game.Player')),
                ('play', models.ManyToManyField(related_name='games', to='game.Game')),
            ],
        ),
    ]
