# Generated by Django 2.2 on 2019-04-27 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Число')),
                ('game_state', models.IntegerField(default=0, verbose_name='Код состояния')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session', models.CharField(max_length=96, verbose_name='Идентификатор сессии')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
            },
        ),
        migrations.CreateModel(
            name='PlayerGameInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_attempts', models.IntegerField(default=0, verbose_name='Число попыток')),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
                ('second_player', models.ManyToManyField(to='game.Player')),
            ],
            options={
                'verbose_name': 'Статистика игры',
                'verbose_name_plural': 'Статистика игр',
            },
        ),
    ]
