# Generated by Django 2.2 on 2019-05-17 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playergameinfo',
            old_name='play',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='playergameinfo',
            old_name='second_player',
            new_name='players',
        ),
    ]
