# Generated by Django 2.2 on 2019-05-17 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20190517_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playergameinfo',
            old_name='game',
            new_name='the_game',
        ),
    ]
