# Generated by Django 2.2 on 2019-05-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20190517_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='user_session',
            field=models.CharField(default=0, max_length=96, verbose_name='Идентификатор сессии'),
        ),
    ]
